# fly.toml app configuration file generated for darius-no on 2023-11-02T19:55:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "darius"
primary_region = "sea"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
